### ISSUE TITLE
docker build 打包出错

### ISSUE THREAD

**Issue by mustang2247** [WongSaang/chatgpt-ui-server#2]
docker build --target wsgi-server -t chatgpt-server-wsgi-server:latest .

docker run --rm -p 9000:8000 chatgpt-server-wsgi-server:latest

报错：
exec ./entrypoint.sh: no such file or directory

**Comment by WongSaang** [comment]
您好，请问您是在 Windows 系统上构建镜像吗？
如果是，应该是文件格式导致的。我已经更新了 Dockerfile，请拉取最新的 Dockerfile 来解决这个问题。

**以下是解决思路：**
Windows 的换行符是 `\r\n` , 而 Linux 的换行符是 `\n`，最新的 Dockerfile 引入了 dos2unix 来转换 entrypoint.sh 的格式，解决在 windows 上构建镜像时报 ./entrypoint.sh: no such file or directory 的问题。

**Comment by mustang2247** [comment]
对的，我的就是 windows 上，另外我们把backend 分成两个image的目的是啥？

**Comment by WongSaang** [comment]
后端使用 Django 框架，需要通过nginx来处理后台的静态文件。
另外在实际部署中，可以通过nginx转发多个wsgi服务，实现负载均衡。

**Comment by mustang2247** [comment]
ok，了解了。前端的代码生产环境是否也可以配置 proxy

**Comment by WongSaang** [comment]
前端项目，有个环境变量配置后端地址。
根目录下有个nginx.conf，也可以直接配。
