### ISSUE TITLE
docker 下载最新镜像报这个错误！CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by unrulpkk** [WongSaang/chatgpt-ui-server#9]
Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True.
![image](https://user-images.githubusercontent.com/129469691/231699955-158c1949-b6cd-4207-af03-12e06a46cdea.png)

**Comment by WongSaang** [comment]
https://wongsaang.github.io/chatgpt-ui/zh/guide/configuration.html#%E5%90%8E%E7%AB%AF-csrf-%E7%99%BD%E5%90%8D%E5%8D%95

https://github.com/WongSaang/chatgpt-ui/issues?q=is%3Aissue+CSRF+
